catalogers:
  - alpm-db-cataloger
  - cargo-auditable-binary-cataloger
  - cocoapods-cataloger
  - conan-cataloger
  - dotnet-deps-cataloger
  - dpkg-db-cataloger
  - elixir-mix-lock-cataloger
  - erlang-rebar-lock-cataloger
  - github-actions-usage-cataloger
  - go-module-file-cataloger
  - go-module-binary-cataloger
  - graalvm-native-image-cataloger
  - haskell-cataloger
  - java-gradle-lockfile-cataloger
  - java-pom-cataloger
  - javascript-lock-cataloger
  - javascript-package-cataloger
  - linux-kernel-cataloger
  - nix-store-cataloger
  - php-composer-installed-cataloger
  - php-composer-lock-cataloger
  - portage-cataloger
  - python-package-cataloger
  - r-package-cataloger
  - rpm-db-cataloger
  - rpm-archive-cataloger
  - ruby-gemfile-cataloger
  - ruby-installed-gemspec-cataloger
  - rust-cargo-lock-cataloger
  - sbom-cataloger