catalogers:
  - binary
  - ruby-gemfile
  - ruby-gemspec
  - python-index
  - python-package
  - javascript-lock
  - javascript-package
  - php-composer-installed
  - php-composer-lock
  - alpmdb
  - dpkgdb
  - rpmdb
  - java
  - java-pom
  - apkdb
  - go-module-binary
  - go-mod-file
  - dartlang-lock
  - rust
  - rust-cargo-lock
  - cocoapods
  - hackage
  - haskell
  - conan
  - dotnet-deps
  - elixir-mix-lock
  - erlang-rebar-lock
  - portage
  - r-package