catalogers:
  - alpmdb
  - apkdb
  - binary
  - cocoapods
  - conan
  - dartlang-lock
  - dotnet-deps
  - dpkgdb
  - elixir-mix-lock
  - erlang-rebar-lock
  - go-mod-file
  - go-module-binary
  - hackage
  - haskell
  - java
  - java-pom
  - javascript-lock
  - javascript-package
  - php-composer-installed
  - php-composer-lock
  - portage
  - python-index
  - python-package
  - r-package
  - rpmdb
  - ruby-gemfile
  - ruby-gemspec
  - rust
  - rust-cargo-lock
  - swift-package-manager